language: python

sudo: false

cache:
  # The cache: pip support does not appear to be working, so we'll just cache
  # the pip cache directory ourselves.
  directories:
    - ~/.cache/pip

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  # Before installation, we'll run ``pip wheel``, this will build wheels for
  # anything that doesn't already have one on PyPI.
  - pip wheel -r requirements.txt
  # Actually install our dependencies now, this will pull from the directory
  # that the first command placed the Wheels into.
  - pip install -r requirements.txt

script: true
